Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controller\\AccueilController",
            "name": "AccueilController",
            "summary": "Controleur\u0020de\u0020la\u0020page\u0020d\u0027accueil",
            "url": "classes/App-Controller-AccueilController.html"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-AccueilController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020page\u0020d\u0027accueil\u0020avec\u0020les\u00202\u0020derni\u00E8res\u0020formations",
            "url": "classes/App-Controller-AccueilController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003Acgu\u0028\u0029",
            "name": "cgu",
            "summary": "Affiche\u0020la\u0020page\u0020des\u0020conditions\u0020g\u00E9n\u00E9rales\u0020d\u0027utilisation",
            "url": "classes/App-Controller-AccueilController.html#method_cgu"
        },                {
            "fqsen": "\\App\\Controller\\AccueilController\u003A\u003A\u0024repository",
            "name": "repository",
            "summary": "",
            "url": "classes/App-Controller-AccueilController.html#property_repository"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminAccueilController",
            "name": "AdminAccueilController",
            "summary": "Controleur\u0020de\u0020la\u0020page\u0020d\u0027accueil\u0020de\u0020l\u0027administration",
            "url": "classes/App-Controller-admin-AdminAccueilController.html"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminAccueilController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-admin-AdminAccueilController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminAccueilController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020page\u0020d\u0027accueil\u0020avec\u0020les\u00202\u0020derni\u00E8res\u0020formations",
            "url": "classes/App-Controller-admin-AdminAccueilController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminAccueilController\u003A\u003Acgu\u0028\u0029",
            "name": "cgu",
            "summary": "Affiche\u0020la\u0020page\u0020des\u0020conditions\u0020g\u00E9n\u00E9rales\u0020d\u0027utilisation",
            "url": "classes/App-Controller-admin-AdminAccueilController.html#method_cgu"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminAccueilController\u003A\u003A\u0024repository",
            "name": "repository",
            "summary": "",
            "url": "classes/App-Controller-admin-AdminAccueilController.html#property_repository"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminCategoriesController",
            "name": "AdminCategoriesController",
            "summary": "Controleur\u0020des\u0020formations\u0020c\u00F4t\u00E9\u0020admin",
            "url": "classes/App-Controller-admin-AdminCategoriesController.html"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminCategoriesController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020contr\u00F4leur.",
            "url": "classes/App-Controller-admin-AdminCategoriesController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminCategoriesController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020liste\u0020compl\u00E8te\u0020de\u0020toutes\u0020les\u0020cat\u00E9gories",
            "url": "classes/App-Controller-admin-AdminCategoriesController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminCategoriesController\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Supprime\u0020une\u0020cat\u00E9gorie\u0020apr\u00E8s\u0020validation\u0020du\u0020token\u0020CSRF.",
            "url": "classes/App-Controller-admin-AdminCategoriesController.html#method_remove"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminCategoriesController\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Ajoute\u0020une\u0020nouvelle\u0020cat\u00E9gorie\u0020apr\u00E8s\u0020validation\u0020du\u0020token\u0020CSRF.",
            "url": "classes/App-Controller-admin-AdminCategoriesController.html#method_add"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminCategoriesController\u003A\u003ARENDER_PATH",
            "name": "RENDER_PATH",
            "summary": "Chemin\u0020vers\u0020le\u0020template\u0020Twig\u0020utilis\u00E9\u0020pour\u0020la\u0020liste\u0020des\u0020cat\u00E9gories\u0020en\u0020administration.",
            "url": "classes/App-Controller-admin-AdminCategoriesController.html#constant_RENDER_PATH"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminCategoriesController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "Repository\u0020des\u0020cat\u00E9gories,\u0020utilis\u00E9\u0020pour\u0020acc\u00E9der\u0020aux\u0020donn\u00E9es\u0020des\u0020cat\u00E9gories.",
            "url": "classes/App-Controller-admin-AdminCategoriesController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminCategoriesController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "Repository\u0020des\u0020formations,\u0020utilis\u00E9\u0020pour\u0020v\u00E9rifier\u0020les\u0020formations\u0020li\u00E9es\u0020\u00E0\u0020une\u0020cat\u00E9gorie.",
            "url": "classes/App-Controller-admin-AdminCategoriesController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminFormationsController",
            "name": "AdminFormationsController",
            "summary": "Controleur\u0020des\u0020formations\u0020c\u00F4t\u00E9\u0020admin",
            "url": "classes/App-Controller-admin-AdminFormationsController.html"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminFormationsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020contr\u00F4leur.",
            "url": "classes/App-Controller-admin-AdminFormationsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminFormationsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020toutes\u0020les\u0020formations\u0020avec\u0020leurs\u0020cat\u00E9gories\ndans\u0020l\u0027interface\u0020d\u0027administration.",
            "url": "classes/App-Controller-admin-AdminFormationsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminFormationsController\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "Affiche\u0020la\u0020liste\u0020des\u0020formations\u0020tri\u00E9es\u0020selon\u0020un\u0020champ\u0020et\u0020un\u0020ordre\u0020donn\u00E9s.",
            "url": "classes/App-Controller-admin-AdminFormationsController.html#method_sort"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminFormationsController\u003A\u003AfindAllContain\u0028\u0029",
            "name": "findAllContain",
            "summary": "Affiche\u0020la\u0020liste\u0020des\u0020formations\u0020dont\u0020un\u0020champ\u0020contient\u0020la\u0020valeur\u0020recherch\u00E9e.",
            "url": "classes/App-Controller-admin-AdminFormationsController.html#method_findAllContain"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminFormationsController\u003A\u003AshowOne\u0028\u0029",
            "name": "showOne",
            "summary": "Affiche\u0020le\u0020d\u00E9tail\u0020d\u0027une\u0020formation\u0020identifi\u00E9e\u0020par\u0020son\u0020identifiant.",
            "url": "classes/App-Controller-admin-AdminFormationsController.html#method_showOne"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminFormationsController\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Supprime\u0020une\u0020formation\u0020apr\u00E8s\u0020validation\u0020du\u0020token\u0020CSRF.",
            "url": "classes/App-Controller-admin-AdminFormationsController.html#method_remove"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminFormationsController\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Affiche\u0020le\u0020formulaire\u0020d\u0027ajout\u0020d\u0027une\u0020nouvelle\u0020formation\u0020et\u0020traite\u0020sa\u0020soumission.",
            "url": "classes/App-Controller-admin-AdminFormationsController.html#method_add"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminFormationsController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Affiche\u0020le\u0020formulaire\u0020de\u0020modification\u0020d\u0027une\u0020formation\u0020existante\u0020et\u0020traite\u0020sa\u0020soumission.",
            "url": "classes/App-Controller-admin-AdminFormationsController.html#method_edit"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminFormationsController\u003A\u003ARENDER_PATH",
            "name": "RENDER_PATH",
            "summary": "Chemin\u0020vers\u0020le\u0020template\u0020Twig\u0020utilis\u00E9\u0020pour\u0020la\u0020liste\u0020des\u0020formations\u0020en\u0020administration.",
            "url": "classes/App-Controller-admin-AdminFormationsController.html#constant_RENDER_PATH"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminFormationsController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "Repository\u0020des\u0020formations,\u0020utilis\u00E9\u0020pour\u0020acc\u00E9der\u0020aux\u0020donn\u00E9es\u0020des\u0020formations.",
            "url": "classes/App-Controller-admin-AdminFormationsController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminFormationsController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "Repository\u0020des\u0020cat\u00E9gories,\u0020utilis\u00E9\u0020pour\u0020acc\u00E9der\u0020aux\u0020donn\u00E9es\u0020des\u0020cat\u00E9gories.",
            "url": "classes/App-Controller-admin-AdminFormationsController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminPlaylistsController",
            "name": "AdminPlaylistsController",
            "summary": "Controleur\u0020des\u0020playlists\u0020c\u00F4t\u00E9\u0020admin",
            "url": "classes/App-Controller-admin-AdminPlaylistsController.html"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminPlaylistsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020contr\u00F4leur.",
            "url": "classes/App-Controller-admin-AdminPlaylistsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminPlaylistsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "\u002A\u0020Affiche\u0020la\u0020liste\u0020compl\u00E8te\u0020de\u0020toutes\u0020les\u0020playlists\u0020tri\u00E9es\u0020par\u0020nom\u0020\u0028ordre\u0020croissant\u0029\navec\u0020leurs\u0020cat\u00E9gories\u0020dans\u0020l\u0027interface\u0020d\u0027administration.",
            "url": "classes/App-Controller-admin-AdminPlaylistsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminPlaylistsController\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "Affiche\u0020la\u0020liste\u0020des\u0020playlists\u0020tri\u00E9es\u0020selon\u0020un\u0020champ\u0020et\u0020un\u0020ordre\u0020donn\u00E9s.",
            "url": "classes/App-Controller-admin-AdminPlaylistsController.html#method_sort"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminPlaylistsController\u003A\u003AfindAllContain\u0028\u0029",
            "name": "findAllContain",
            "summary": "Affiche\u0020la\u0020liste\u0020des\u0020playlists\u0020dont\u0020un\u0020champ\u0020contient\u0020la\u0020valeur\u0020recherch\u00E9e.",
            "url": "classes/App-Controller-admin-AdminPlaylistsController.html#method_findAllContain"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminPlaylistsController\u003A\u003AshowOne\u0028\u0029",
            "name": "showOne",
            "summary": "Affiche\u0020le\u0020d\u00E9tail\u0020d\u0027une\u0020playlist\u0020identifi\u00E9e\u0020par\u0020son\u0020identifiant\navec\u0020ses\u0020formations\u0020et\u0020ses\u0020cat\u00E9gories\u0020associ\u00E9es.",
            "url": "classes/App-Controller-admin-AdminPlaylistsController.html#method_showOne"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminPlaylistsController\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Affiche\u0020le\u0020formulaire\u0020d\u0027ajout\u0020d\u0027une\u0020nouvelle\u0020playlist\u0020et\u0020traite\u0020sa\u0020soumission.",
            "url": "classes/App-Controller-admin-AdminPlaylistsController.html#method_add"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminPlaylistsController\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Supprime\u0020une\u0020playlist\u0020apr\u00E8s\u0020validation\u0020du\u0020token\u0020CSRF.",
            "url": "classes/App-Controller-admin-AdminPlaylistsController.html#method_remove"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminPlaylistsController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Affiche\u0020le\u0020formulaire\u0020de\u0020modification\u0020d\u0027une\u0020playlist\u0020existante\u0020et\u0020traite\u0020sa\u0020soumission.",
            "url": "classes/App-Controller-admin-AdminPlaylistsController.html#method_edit"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminPlaylistsController\u003A\u003ARENDER_PATH",
            "name": "RENDER_PATH",
            "summary": "Chemin\u0020vers\u0020le\u0020template\u0020Twig\u0020utilis\u00E9\u0020pour\u0020la\u0020liste\u0020des\u0020playlists\u0020en\u0020administration.",
            "url": "classes/App-Controller-admin-AdminPlaylistsController.html#constant_RENDER_PATH"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminPlaylistsController\u003A\u003A\u0024playlistRepository",
            "name": "playlistRepository",
            "summary": "Repository\u0020des\u0020playlists,\u0020utilis\u00E9\u0020pour\u0020acc\u00E9der\u0020aux\u0020donn\u00E9es\u0020des\u0020playlists.",
            "url": "classes/App-Controller-admin-AdminPlaylistsController.html#property_playlistRepository"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminPlaylistsController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "Repository\u0020des\u0020formations,\u0020utilis\u00E9\u0020pour\u0020acc\u00E9der\u0020aux\u0020formations\u0020d\u0027une\u0020playlist.",
            "url": "classes/App-Controller-admin-AdminPlaylistsController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\admin\\AdminPlaylistsController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "Repository\u0020des\u0020cat\u00E9gories,\u0020utilis\u00E9\u0020pour\u0020acc\u00E9der\u0020aux\u0020cat\u00E9gories\u0020des\u0020playlists.",
            "url": "classes/App-Controller-admin-AdminPlaylistsController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController",
            "name": "FormationsController",
            "summary": "Controleur\u0020des\u0020formations",
            "url": "classes/App-Controller-FormationsController.html"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020contr\u00F4leur.",
            "url": "classes/App-Controller-FormationsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020toutes\u0020les\u0020formations\u0020et\u0020leurs\u0020cat\u00E9gories.",
            "url": "classes/App-Controller-FormationsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "Affiche\u0020la\u0020liste\u0020des\u0020formations\u0020tri\u00E9es\u0020selon\u0020un\u0020champ\u0020et\u0020un\u0020ordre\u0020donn\u00E9s.",
            "url": "classes/App-Controller-FormationsController.html#method_sort"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AfindAllContain\u0028\u0029",
            "name": "findAllContain",
            "summary": "Affiche\u0020toutes\u0020les\u0020formations\u0020dont\u0020un\u0020champ\u0020contient\u0020la\u0020valeur\u0020recherch\u00E9e.",
            "url": "classes/App-Controller-FormationsController.html#method_findAllContain"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003AshowOne\u0028\u0029",
            "name": "showOne",
            "summary": "Affiche\u0020le\u0020d\u00E9tail\u0020d\u0027une\u0020formation\u0020identifi\u00E9e\u0020par\u0020son\u0020identifiant.",
            "url": "classes/App-Controller-FormationsController.html#method_showOne"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003ARENDER_PATH",
            "name": "RENDER_PATH",
            "summary": "Chemin\u0020vers\u0020le\u0020template\u0020Twig\u0020utilis\u00E9\u0020pour\u0020la\u0020liste\u0020des\u0020formations.",
            "url": "classes/App-Controller-FormationsController.html#constant_RENDER_PATH"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "Repository\u0020des\u0020formations,\u0020utilis\u00E9\u0020pour\u0020acc\u00E9der\u0020aux\u0020donn\u00E9es\u0020des\u0020formations.",
            "url": "classes/App-Controller-FormationsController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\FormationsController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "Repository\u0020des\u0020cat\u00E9gories,\u0020utilis\u00E9\u0020pour\u0020acc\u00E9der\u0020aux\u0020donn\u00E9es\u0020des\u0020cat\u00E9gories.",
            "url": "classes/App-Controller-FormationsController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController",
            "name": "PlaylistsController",
            "summary": "Controleur\u0020des\u0020playlists",
            "url": "classes/App-Controller-PlaylistsController.html"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Affiche\u0020la\u0020liste\u0020de\u0020toutes\u0020les\u0020playlists",
            "url": "classes/App-Controller-PlaylistsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003Asort\u0028\u0029",
            "name": "sort",
            "summary": "Affiche\u0020les\u0020playlists\u0020tri\u00E9es",
            "url": "classes/App-Controller-PlaylistsController.html#method_sort"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003AfindAllContain\u0028\u0029",
            "name": "findAllContain",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#method_findAllContain"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003AshowOne\u0028\u0029",
            "name": "showOne",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#method_showOne"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003ARENDER_PATH",
            "name": "RENDER_PATH",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#constant_RENDER_PATH"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003A\u0024playlistRepository",
            "name": "playlistRepository",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#property_playlistRepository"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003A\u0024formationRepository",
            "name": "formationRepository",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#property_formationRepository"
        },                {
            "fqsen": "\\App\\Controller\\PlaylistsController\u003A\u003A\u0024categorieRepository",
            "name": "categorieRepository",
            "summary": "",
            "url": "classes/App-Controller-PlaylistsController.html#property_categorieRepository"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController",
            "name": "SecurityController",
            "summary": "Contr\u00F4leur\u0020g\u00E9rant\u0020l\u0027authentification\u0020des\u0020utilisateurs.",
            "url": "classes/App-Controller-SecurityController.html"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Affiche\u0020le\u0020formulaire\u0020de\u0020connexion\u0020et\u0020g\u00E8re\u0020les\u0020erreurs\u0020d\u0027authentification.",
            "url": "classes/App-Controller-SecurityController.html#method_login"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "",
            "url": "classes/App-Controller-SecurityController.html#method_logout"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures",
            "name": "AppFixtures",
            "summary": "Classe\u0020de\u0020fixtures\u0020pour\u0020l\u0027application.",
            "url": "classes/App-DataFixtures-AppFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-DataFixtures-AppFixtures.html#method___construct"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Constructeur\u0020de\u0020la\u0020classe\u0020AppFixtures.",
            "url": "classes/App-DataFixtures-AppFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures\u003A\u003A\u0024hasher",
            "name": "hasher",
            "summary": "Service\u0020de\u0020hachage\u0020des\u0020mots\u0020de\u0020passe,\u0020utilis\u00E9\u0020pour\u0020s\u00E9curiser\u0020le\u0020mot\u0020de\u0020passe\u0020de\u0020l\u0027admin.",
            "url": "classes/App-DataFixtures-AppFixtures.html#property_hasher"
        },                {
            "fqsen": "\\App\\Entity\\Categorie",
            "name": "Categorie",
            "summary": "Entit\u00E9\u0020repr\u00E9sentant\u0020une\u0020cat\u00E9gorie.",
            "url": "classes/App-Entity-Categorie.html"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AgetFormations\u0028\u0029",
            "name": "getFormations",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_getFormations"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AaddFormation\u0028\u0029",
            "name": "addFormation",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_addFormation"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003AremoveFormation\u0028\u0029",
            "name": "removeFormation",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#method_removeFormation"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\Categorie\u003A\u003A\u0024formations",
            "name": "formations",
            "summary": "",
            "url": "classes/App-Entity-Categorie.html#property_formations"
        },                {
            "fqsen": "\\App\\Entity\\Formation",
            "name": "Formation",
            "summary": "Entit\u00E9\u0020repr\u00E9sentant\u0020une\u0020formation.",
            "url": "classes/App-Entity-Formation.html"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPublishedAt\u0028\u0029",
            "name": "getPublishedAt",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getPublishedAt"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetPublishedAt\u0028\u0029",
            "name": "setPublishedAt",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setPublishedAt"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPublishedAtString\u0028\u0029",
            "name": "getPublishedAtString",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getPublishedAtString"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getDescription"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetVideoId\u0028\u0029",
            "name": "getVideoId",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getVideoId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetVideoId\u0028\u0029",
            "name": "setVideoId",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setVideoId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetMiniature\u0028\u0029",
            "name": "getMiniature",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getMiniature"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPicture\u0028\u0029",
            "name": "getPicture",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getPicture"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetPlaylist\u0028\u0029",
            "name": "getPlaylist",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getPlaylist"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AsetPlaylist\u0028\u0029",
            "name": "setPlaylist",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_setPlaylist"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AgetCategories\u0028\u0029",
            "name": "getCategories",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_getCategories"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AaddCategory\u0028\u0029",
            "name": "addCategory",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_addCategory"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003AremoveCategory\u0028\u0029",
            "name": "removeCategory",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#method_removeCategory"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003ACHEMIN_IMAGE",
            "name": "CHEMIN_IMAGE",
            "summary": "D\u00E9but\u0020de\u0020chemin\u0020vers\u0020les\u0020images",
            "url": "classes/App-Entity-Formation.html#constant_CHEMIN_IMAGE"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024publishedAt",
            "name": "publishedAt",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_publishedAt"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_title"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_description"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024videoId",
            "name": "videoId",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_videoId"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024playlist",
            "name": "playlist",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_playlist"
        },                {
            "fqsen": "\\App\\Entity\\Formation\u003A\u003A\u0024categories",
            "name": "categories",
            "summary": "",
            "url": "classes/App-Entity-Formation.html#property_categories"
        },                {
            "fqsen": "\\App\\Entity\\Playlist",
            "name": "Playlist",
            "summary": "Entit\u00E9\u0020repr\u00E9sentant\u0020une\u0020playlist\u0020de\u0020formations.",
            "url": "classes/App-Entity-Playlist.html"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getDescription"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetFormations\u0028\u0029",
            "name": "getFormations",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getFormations"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetNombreFormations\u0028\u0029",
            "name": "getNombreFormations",
            "summary": "retourne\u0020le\u0020nombre\u0020de\u0020formations\u0020dans\u0020la\u0020playlist",
            "url": "classes/App-Entity-Playlist.html#method_getNombreFormations"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AaddFormation\u0028\u0029",
            "name": "addFormation",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_addFormation"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AremoveFormation\u0028\u0029",
            "name": "removeFormation",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_removeFormation"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003AgetCategoriesPlaylist\u0028\u0029",
            "name": "getCategoriesPlaylist",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#method_getCategoriesPlaylist"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#property_description"
        },                {
            "fqsen": "\\App\\Entity\\Playlist\u003A\u003A\u0024formations",
            "name": "formations",
            "summary": "",
            "url": "classes/App-Entity-Playlist.html#property_formations"
        },                {
            "fqsen": "\\App\\Entity\\User",
            "name": "User",
            "summary": "Entit\u00E9\u0020repr\u00E9sentant\u0020un\u0020utilisateur\u0020de\u0020l\u0027application.",
            "url": "classes/App-Entity-User.html"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUsername\u0028\u0029",
            "name": "getUsername",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetUsername\u0028\u0029",
            "name": "setUsername",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUserIdentifier\u0028\u0029",
            "name": "getUserIdentifier",
            "summary": "l\u0027identifiant\u0020visuel\u0020repr\u00E9sentant\u0020l\u0027utilisateur.",
            "url": "classes/App-Entity-User.html#method_getUserIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetRoles\u0028\u0029",
            "name": "getRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetRoles\u0028\u0029",
            "name": "setRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AeraseCredentials\u0028\u0029",
            "name": "eraseCredentials",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_eraseCredentials"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_username"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024roles",
            "name": "roles",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_roles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_password"
        },                {
            "fqsen": "\\App\\Form\\FormationType",
            "name": "FormationType",
            "summary": "Formulaire\u0020de\u0020cr\u00E9ation\u0020et\u0020de\u0020modification\u0020d\u0027une\u0020formation.",
            "url": "classes/App-Form-FormationType.html"
        },                {
            "fqsen": "\\App\\Form\\FormationType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "Construit\u0020le\u0020formulaire\u0020de\u0020cr\u00E9ation\/modification\u0020d\u0027une\u0020formation.",
            "url": "classes/App-Form-FormationType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\FormationType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-FormationType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\PlaylistType",
            "name": "PlaylistType",
            "summary": "Formulaire\u0020de\u0020cr\u00E9ation\u0020et\u0020de\u0020modification\u0020d\u0027une\u0020playlist.",
            "url": "classes/App-Form-PlaylistType.html"
        },                {
            "fqsen": "\\App\\Form\\PlaylistType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "Construit\u0020le\u0020formulaire\u0020de\u0020cr\u00E9ation\/modification\u0020d\u0027une\u0020playlist.",
            "url": "classes/App-Form-PlaylistType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\PlaylistType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "Configure\u0020les\u0020options\u0020par\u0020d\u00E9faut\u0020du\u0020formulaire.",
            "url": "classes/App-Form-PlaylistType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository",
            "name": "CategorieRepository",
            "summary": "Repository\u0020pour\u0020l\u0027entit\u00E9\u0020Categorie.",
            "url": "classes/App-Repository-CategorieRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020repository.",
            "url": "classes/App-Repository-CategorieRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Ajoute\u0020une\u0020nouvelle\u0020cat\u00E9gorie\u0020\u00E0\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Repository-CategorieRepository.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Supprime\u0020une\u0020cat\u00E9gorie\u0020de\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Repository-CategorieRepository.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\CategorieRepository\u003A\u003AfindAllForOnePlaylist\u0028\u0029",
            "name": "findAllForOnePlaylist",
            "summary": "Retourne\u0020la\u0020liste\u0020des\u0020cat\u00E9gories\u0020des\u0020formations\u0020d\u0027une\u0020playlist\ntri\u00E9es\u0020par\u0020nom\u0020de\u0020cat\u00E9gorie\u0020par\u0020ordre\u0020croissant.",
            "url": "classes/App-Repository-CategorieRepository.html#method_findAllForOnePlaylist"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository",
            "name": "FormationRepository",
            "summary": "Repository\u0020pour\u0020l\u0027entit\u00E9\u0020Formation.",
            "url": "classes/App-Repository-FormationRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020repository.",
            "url": "classes/App-Repository-FormationRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Ajoute\u0020une\u0020nouvelle\u0020formation\u0020\u00E0\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Repository-FormationRepository.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Supprime\u0020une\u0020formation\u0020de\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Repository-FormationRepository.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllOrderBy\u0028\u0029",
            "name": "findAllOrderBy",
            "summary": "Retourne\u0020toutes\u0020les\u0020formations\u0020tri\u00E9es\u0020sur\u0020un\u0020champ\u0020donn\u00E9.",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllOrderBy"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindByContainValue\u0028\u0029",
            "name": "findByContainValue",
            "summary": "Enregistrements\u0020dont\u0020un\u0020champ\u0020contient\u0020une\u0020valeur\nou\u0020tous\u0020les\u0020enregistrements\u0020si\u0020la\u0020valeur\u0020est\u0020vide",
            "url": "classes/App-Repository-FormationRepository.html#method_findByContainValue"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllLasted\u0028\u0029",
            "name": "findAllLasted",
            "summary": "Retourne\u0020les\u0020n\u0020formations\u0020les\u0020plus\u0020r\u00E9centes,\u0020tri\u00E9es\u0020par\u0020date\u0020de\u0020publication\u0020d\u00E9croissante.",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllLasted"
        },                {
            "fqsen": "\\App\\Repository\\FormationRepository\u003A\u003AfindAllForOnePlaylist\u0028\u0029",
            "name": "findAllForOnePlaylist",
            "summary": "Retourne\u0020la\u0020liste\u0020des\u0020formations\u0020d\u0027une\u0020playlist\ntri\u00E9es\u0020par\u0020date\u0020de\u0020publication\u0020croissante.",
            "url": "classes/App-Repository-FormationRepository.html#method_findAllForOnePlaylist"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository",
            "name": "PlaylistRepository",
            "summary": "Repository\u0020pour\u0020l\u0027entit\u00E9\u0020Playlist.",
            "url": "classes/App-Repository-PlaylistRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020repository.",
            "url": "classes/App-Repository-PlaylistRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Ajoute\u0020une\u0020nouvelle\u0020playlist\u0020\u00E0\u0020la\u0020base\u0020de\u0020donn\u00E9es",
            "url": "classes/App-Repository-PlaylistRepository.html#method_add"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Supprime\u0020une\u0020playlist\u0020de\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Repository-PlaylistRepository.html#method_remove"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindAllOrderByName\u0028\u0029",
            "name": "findAllOrderByName",
            "summary": "Retourne\u0020toutes\u0020les\u0020playlists\u0020tri\u00E9es\u0020sur\u0020le\u0020nom\u0020de\u0020la\u0020playlist",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findAllOrderByName"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindAllOrderByNumberFormations\u0028\u0029",
            "name": "findAllOrderByNumberFormations",
            "summary": "Retourne\u0020toutes\u0020les\u0020playlists\u0020tri\u00E9es\u0020par\u0020le\u0020nombre\u0020de\u0020formations",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findAllOrderByNumberFormations"
        },                {
            "fqsen": "\\App\\Repository\\PlaylistRepository\u003A\u003AfindByContainValue\u0028\u0029",
            "name": "findByContainValue",
            "summary": "Enregistrements\u0020dont\u0020un\u0020champ\u0020contient\u0020une\u0020valeur\nou\u0020tous\u0020les\u0020enregistrements\u0020si\u0020la\u0020valeur\u0020est\u0020vide",
            "url": "classes/App-Repository-PlaylistRepository.html#method_findByContainValue"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository",
            "name": "UserRepository",
            "summary": "Repository\u0020pour\u0020l\u0027entit\u00E9\u0020User.",
            "url": "classes/App-Repository-UserRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020repository.",
            "url": "classes/App-Repository-UserRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003AupgradePassword\u0028\u0029",
            "name": "upgradePassword",
            "summary": "Met\u0020\u00E0\u0020jour\u0020\u0028re\u002Dhache\u0029\u0020automatiquement\u0020le\u0020mot\u0020de\u0020passe\u0020de\u0020l\u0027utilisateur\u0020au\u0020fil\u0020du\u0020temps.",
            "url": "classes/App-Repository-UserRepository.html#method_upgradePassword"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator",
            "name": "AppAuthenticator",
            "summary": "G\u00E8re\u0020l\u0027authentification\u0020des\u0020utilisateurs\u0020via\u0020un\u0020formulaire\u0020de\u0020connexion.",
            "url": "classes/App-Security-AppAuthenticator.html"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Security-AppAuthenticator.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "",
            "url": "classes/App-Security-AppAuthenticator.html#method_authenticate"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator\u003A\u003AonAuthenticationSuccess\u0028\u0029",
            "name": "onAuthenticationSuccess",
            "summary": "G\u00E8re\u0020la\u0020redirection\u0020apr\u00E8s\u0020une\u0020authentification\u0020r\u00E9ussie.",
            "url": "classes/App-Security-AppAuthenticator.html#method_onAuthenticationSuccess"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator\u003A\u003AgetLoginUrl\u0028\u0029",
            "name": "getLoginUrl",
            "summary": "",
            "url": "classes/App-Security-AppAuthenticator.html#method_getLoginUrl"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator\u003A\u003ALOGIN_ROUTE",
            "name": "LOGIN_ROUTE",
            "summary": "Nom\u0020de\u0020la\u0020route\u0020de\u0020connexion\u0020utilis\u00E9e\u0020pour\u0020la\u0020page\u0020login.",
            "url": "classes/App-Security-AppAuthenticator.html#constant_LOGIN_ROUTE"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator\u003A\u003A\u0024urlGenerator",
            "name": "urlGenerator",
            "summary": "",
            "url": "classes/App-Security-AppAuthenticator.html#property_urlGenerator"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\Controller\\admin",
            "name": "admin",
            "summary": "",
            "url": "namespaces/app-controller-admin.html"
        },                {
            "fqsen": "\\App\\DataFixtures",
            "name": "DataFixtures",
            "summary": "",
            "url": "namespaces/app-datafixtures.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App\\Form",
            "name": "Form",
            "summary": "",
            "url": "namespaces/app-form.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        },                {
            "fqsen": "\\App\\Security",
            "name": "Security",
            "summary": "",
            "url": "namespaces/app-security.html"
        }            ]
);
